groups:
- name: disk-alerts
  rules:
  - alert: NodeDiskUsageHigh
    expr: |
      100 * (1 - (
        node_filesystem_avail_bytes{fstype!~"tmpfs|overlay|squashfs|aufs|nsfs",mountpoint!~"/run.*|/var/lib/docker/.*|/var/lib/containerd/.*"}
        /
        node_filesystem_size_bytes{fstype!~"tmpfs|overlay|squashfs|aufs|nsfs",mountpoint!~"/run.*|/var/lib/docker/.*|/var/lib/containerd/.*"}
      )) > 90
    for: 1m
    labels:
      severity: critical
    annotations:
      summary: "Disk usage is {{ printf \"%.1f\" $value }}% on {{ $labels.host }}, Mountpoint: {{ $labels.mountpoint }} ({{ $labels.device }})."
      silence_matchers: "alertname%3DNodeDiskUsageHigh&matcher=host%3D{{ $labels.host }}&matcher=mountpoint%3D{{ $labels.mountpoint }}"
