groups:
  - name: host-availability
    rules:
      - alert: HostDown
        expr: |
          max_over_time(up{job="node-exporter"}[30m]) == 0
        for: 0s
        labels:
          severity: critical
        annotations:
          summary: "The {{ $labels.instance }} instance is Down."
          description: "No successful node-exporter scrape for 30 minutes."
          silence_matchers: "alertname%3DHostDown&matcher=instance%3D{{ $labels.instance }}"
