{
 "title": "Service Log",
 "description": "Universal and flexible dashboard for logging (extended with compose_project and host filters)",
 "tags": [ "loki" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_LOKI", "label": "datasource" },
   { "name": "service_search", "label": "Service Name Contains:" },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values({serviceName=~\".+\"}, serviceName)"
   },
   {
    "name": "level",
    "label": "Level",
    "query": "label_values({serviceName=~\"$service\"}, level)"
   },
   { "name": "search", "label": "Log Messages Contains:" }
  ]
 },
 "panels": [
  {
   "title": "Total  Count of logs",
   "type": "singlestat",
   "description": "Total  Count of log lines in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({serviceName=~\".*$service_search.*\", serviceName=~\"$service\", level=~\"$level\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Total Count: of $search",
   "type": "singlestat",
   "description": "Total Count: of $search in the specified time range",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(count_over_time(({serviceName=~\".*$service_search.*\", serviceName=~\"$service\", level=~\"$level\"} |= \"$search\")[$__interval]))"
    }
   ]
  },
  {
   "title": "Live logs",
   "type": "logs",
   "description": "Live logs is a like 'tail -f' in a real time",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{serviceName=~\".*$service_search.*\", serviceName=~\"$service\", level=~\"$level\"} |= \"$search\" | json message=\"message\" | line_format \"[{{.serviceName}}] [{{.fileName}}] {{.level}}: {{.message}}\""
    }
   ]
  },
  {
   "title": "Total count of stderr / stdout pie",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum by (serviceName) (count_over_time({serviceName=~\".*$service_search.*\", serviceName=~\"$service\", level=~\"$level\"}[$__interval]))",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "Matched word: \"$search\" donut",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 12, "x": 7, "y": 12 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum by (serviceName) (count_over_time({serviceName=~\".*$service_search.*\", serviceName=~\"$service\", level=~\"$level\"}[$__interval]))",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "\"$search\" Percentage for specified time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time(({serviceName=~\".*$service_search.*\", serviceName=~\"$service\", level=~\"$level\"} |= \"$search\")[$__interval])) * 100 / sum(count_over_time(({serviceName=~\".*$service_search.*\", serviceName=~\"$service\", level=~\"$level\"})[$__interval]))"
    }
   ]
  },
  {
   "title": "Matched word: \"$search\" historical",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum by (serviceName) (count_over_time(({serviceName=~\".*$service_search.*\", serviceName=~\"$service\", level=~\"$level\"} |= \"$search\")[$__interval]))",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "\"$search\" Rate per Pod",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (serviceName) (rate(({serviceName=~\".*$service_search.*\", serviceName=~\"$service\", level=~\"$level\"} |= \"$search\")[30s]))",
     "legendFormat": "{{serviceName}}"
    }
   ]
  },
  {
   "title": "Count of stderr / stdout historical",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (serviceName) (count_over_time({serviceName=~\".*$service_search.*\", serviceName=~\"$service\", level=~\"$level\"}[$__interval]))",
     "legendFormat": "{{serviceName}}"
    }
   ]
  }
 ]
}