apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    orgId: 1
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true

  - name: Loki
    uid: loki
    orgId: 1
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true

  - name: Alertmanager
    uid: alertmanager
    orgId: 1
    type: alertmanager
    access: proxy
    url: http://alertmanager:9093
    editable: true
