name: Mirroring

on:
  push:
    branches:
      - master
      - dev
    tags:
        - '*'

jobs:
  git-sync:
    uses: rosen-bridge/operation/.github/workflows/mirroring-reusable.yml@master
    secrets: inherit
